BACKGROUND_COLOR = (200,200,200)
BAR_COLOR = (0,0,255)

WIDTH, HEIGHT = 900, 500
OUTERMARGINRATIO = 0.1

DRAWRANGEWIDTH = (WIDTH*OUTERMARGINRATIO,WIDTH - WIDTH*OUTERMARGINRATIO)

DRAWRANGEHEIGHT = (HEIGHT*OUTERMARGINRATIO,HEIGHT - HEIGHT*OUTERMARGINRATIO)

# 20 arbitraty spacing between the two graphs
DRAWRANGEWIDTH_GRAPH1 = (DRAWRANGEWIDTH[0],WIDTH/2)
DRAWRANGEWIDTH_GRAPH2 = (WIDTH/2,DRAWRANGEWIDTH[1])

GRAPH1_COLOR = (0,0,255)
GRAPH2_COLOR = (255,0,0)

SPACEBETWEENBOXESRATIO = 0.1

INITIALTIMEBETWEENSWAPS = 100
LISTSIZE = 50

BUBBLE,MERGE = 0,1


ALGO = MERGE

FPSCAP = 60