BACKGROUND_COLOR = (200,200,200)
BAR_COLOR = (0,0,255)

WIDTH, HEIGHT = 900, 500
OUTERMARGINRATIO = 0.1

DRAWRANGEWIDTH = (WIDTH*OUTERMARGINRATIO,WIDTH - WIDTH*OUTERMARGINRATIO)
DRAWRANGEHEIGHT = (HEIGHT*OUTERMARGINRATIO,HEIGHT - HEIGHT*OUTERMARGINRATIO)

SPACEBETWEENBOXESRATIO = 0.1

TIMEBETWEENSWAPS = 2
LISTSIZE = 300

BUBBLE,MERGE = 0,1


ALGO = MERGE

FPSCAP = 60